[build]
  base = "app/frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://piys-backend.up.railway.app"
  # Replace with your actual backend URL when deployed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { REACT_APP_API_URL = "https://piys-backend.up.railway.app" }

[context.deploy-preview]
  environment = { REACT_APP_API_URL = "https://piys-backend.up.railway.app" }

[context.branch-deploy]
  environment = { REACT_APP_API_URL = "https://piys-backend.up.railway.app" }